add insert feature and meta helper

diff --git a/helper/validation b/helper/validation
--- a/helper/validation
+++ b/helper/validation
@@ -12,6 +12,18 @@ function check_positive()
 }
 
 
+function table_exits()
+{
+  if [[ -f "$1" ]]; then
+    return 0 # Exists
+  else
+    echo "file not exist"
+    return 1 # Does not exist
+  fi
+}
+
+
+
 function check_range()
 {
     # $1 number
@@ -41,5 +53,17 @@ function check_starting_string()
             return 1
             
     fi
+    return 0
+}
+
+
+function check_int()
+{
+    # $1 represent number that we want to check
+    if ! [[ $1 =~ ^-?[0-9]+$ ]]; then
+        echo "Invalid input. Please enter a valid number."
+        return 1
+    fi
+
     return 0
 }
